### ISSUE TITLE
Zombie task that cannot be stopped or deleted

### ISSUE THREAD

**Issue by Windowsfreak** [rishikanthc/Scriberr#232]
In one occasion I had a zombie task that was stuck "in progress" forever, but the UI fails to kill (because the process was not running) and fails to stop (because it could not delete the audio file). However both the audio file and even the transcript was to be found in the data folder...

I had to delete the scriberr.db file to get the app into a clean working state again, since this also reduced the number of parallel tasks in the queue.

**Comment by chennessey97** [comment]
I also have been experiencing this, even after finishing all the transcriptions it will start re-transcribing files that were already completed and some don't finish again. It seems to me if the Auto-Transcribe setting being turned on might be causing this but I really don't know. Clearing my cache or the db seems to be the temp fix.

**Comment by rishikanthc** [comment]
I think I have fixed this..  From my debugging I think the issue was caused by the server not resetting jobs left in the "processing" state after a restart or crash. These jobs persisted in the database as "in progress" but had no corresponding active process in memory, making them impossible to control via the UI. So I'm now ensuring the server identifies and marks these "zombie" jobs as failed immediately upon startup. Hopefully this should prevent this from happening again.. Feel free to reopen the issue if you face it again.. 

Apologies for the bug and thanks for bringing this up

**Comment by chennessey97** [comment]
Hello @rishikanthc , thank you for pushing a fix, I did notice improved performance afterwards and am able to delete the jobs that keep running. However, I am retesting and still notice some issues persisting after consuming the fix, maybe this is unrelated but it seems similar. Here are some screenshots but I am happy to provide additional information if that would help, and if there is something I should be doing differently let me know. 

Before uploading I have one completed job from a week ago. 
<img width="1503" height="644" alt="Image" src="https://github.com/user-attachments/assets/75c6e641-242b-4560-aeeb-3888d879b9ca" />

After uploading 9 audio files, I have the auto-transcribe setting disabled so I clicked into each and selected transcribe with my default profile. They are queued up and it starts transcribing them all. 
<img width="920" height="906" alt="Image" src="https://github.com/user-attachments/assets/c2453fb3-92e5-4c4a-8ce7-786f6b63a17d" />


After completing all 9 new transcription jobs, it starts re-doing completed jobs. 
<img width="936" height="981" alt="Image" src="https://github.com/user-attachments/assets/8236407d-ea5a-4319-b22e-b0c9b2adae43" />

<img width="933" height="956" alt="Image" src="https://github.com/user-attachments/assets/e9d2597d-b0e1-49ca-bd1c-118b530c0d7c" />

Even after stopping the jobs that keep running, it restarts other completed jobs in the list. 
<img width="945" height="949" alt="Image" src="https://github.com/user-attachments/assets/97d43c5b-3644-4b92-aa7f-e627aef125e2" />

When I upload in bulk and transcribe them one at a time this issue does not occur, but when I have a list of transcription jobs queued up, that's when this issue occurs. Let me know what your thoughts are or if you/other users have also seen this. 

Thank you for your everything you're doing! Love the app!
